---
format: revealjs
self-contained: true
---

# Chapter 5

::: {style="font-size: 250%;"}
Estimation
:::

## Introduction

In this chapter, we will learn methods for estimating parameters instead of guessing.

- Method of Moments estimation
- Maximum Likelihood estimation

# 5.1

::: {style="font-size: 250%;"}
Method of Moments Estimators (MMEs)
:::

# 5.1.1

::: {style="font-size: 250%;"}
The idea
:::

## Background

Method of moments estimators are constructed by:

- Equating the moments of a population's distribution with the sample moments.
- Solving for the unknown parameters.
- Use as many moments as you need in order to solve for all parameters.

Typically, we start with the lower moments first.

- i.e., $k = 1$ first, then $k=2$ if necessary, then $k=3$ if still necessary, etc.

## Definition 5.1.1

The **$k$th population (distribution) moment** of $X$, for $k=1,2,\ldots$, is denoted by $\mu_k$, and defined as
$$
\mu_k := E[X^k].
$$

Note that $\mu_1 = E[X^1] = \mu$.


## Definition 5.1.2

The **$k$th sample moment** of $X$, for $k=1,2,\ldots$, is denoted by $M_k$, and defined as
$$
M_k := \frac{1}{n}\sum_{i=1}^n X_i^k.
$$

Note that $M_1 = \bar{X}$.

# 5.1.2

::: {style="font-size: 250%;"}
Examples
:::

## Example 5.1.1

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} \text{Exponential}(\lambda)$. 

Find an MME of $\lambda$.

## Example 5.1.1 (cont)

## Example 5.1.2

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} \text{Gamma}(\alpha, \beta)$. 

Find MMEs of $\alpha$ and $\beta$.

## Example 5.1.2 (cont)

## Example 5.1.2 (cont)

## Example 5.1.2 (cont)

# 5.1.3

::: {style="font-size: 250%;"}
Properties of MMEs
:::

## Pros of MMEs

 - Intuitive
 - Easy to find, overall.
 - Usually consistent.
 - Usually asymptotically normal.
 
## Cons of MMEs

- Often biased.
- Not uniquely defined.
- May be outside of the parameter space.
- May not exist.

## Example 5.1.1 continued

In Example 5.1.1, we derived the MME $\hat{\lambda} = \bar{X}$ for an $\text{Exponential}{\lambda}$ population.

What can we say about the convergence of the estimator?

## Example 5.1.1 (cont)

## Example 5.1.1 (cont)

## Example 5.1.2 continued

In Example 5.1.2, we derived the MME estimator
$$
\hat{\alpha} = \frac{\bar{X}^2}{\frac{1}{n}\sum_{i=1}^n X_i^2 - \bar{X}^2} = \frac{M_1^2}{M_2 - M_1^2}.
$$

## Example 5.1.2 (cont)

## Example 5.1.2 (cont)

## Some thoughts

- The WLLN gives us that $M_k \stackrel{P}{\to} \mu_k$ as long as $\text{var}(X^k)$ is finite.
- Asymptotic normality using the CLT and combining the WLLN with the Delta Method.
- MMEs are not well-defined. We could use the second moments to derive an estimator instead of the first.
- MMEs may take values that fall outside the parameter space.
- MMEs may not exist if moments don't exist (i.e., aren't finite).

# 5.2

::: {style="font-size: 250%;"}
Maximum Likelihood Estimators
:::

## Idea

A maximum likelihood estimator (MLE) estimates an unknown parameter with the value whose associated model is most likely to have produced the observed data.

## The joint density

In general, for fixed $\stackrel{\rightarrow}{x} = (x_1, x_2, \ldots, x_n)$, the joint density is defined as
$$
f(\stackrel{\rightarrow}{x}; \theta) = f(x_1, x_2, \ldots, x_n; \theta).
$$

Note that $\theta$ is assumed fixed in the density function since its value is conditional on $\theta$.

## Joint density versus likelihood function

Mathematically, the joint density and the likelihood function are identical.

Conceptually, the likelihood function differs from the joint density in that $\theta$ is assumed to be unknown and the data, $\stackrel{\rightarrow}{x} = (x_1, x_2, \ldots, x_n)$ are fixed.

## The likelihood function

The likelihood function is denoted
$$
L(\theta) = L(\theta; \stackrel{\rightarrow}{x}) = f(\stackrel{\rightarrow}{x}; \theta).
$$

Note that $\theta$ is assumed fixed in the density function since its value is conditional on $\theta$.

## Definition 5.2.1

Suppose that $X_1, X_2, \ldots, X_n$ have joint pdf $f(\stackrel{\rightarrow}{x}; \theta)$.

A **likelihood function** is denoted by $L(\theta)$ is defined as any function proportional to $f(\stackrel{\rightarrow}{x}; \theta)$ when thought of as a function of $\theta$.

The **maximum likelihood estimator** of $\theta$ is the value of $\theta$ that maximizes $L(\theta)$.

# 5.2.1

::: {style="font-size: 250%;"}
Examples
:::

## Example 5.2.2

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} \text{Bernoulli}(p)$. Determine the MLE of $p$.

## Example 5.2.2 (cont)

## Example 5.2.2 (cont)

## Notation

Given a likelihood function $L(\theta)$, we denote the log-likelihood function by
$$
\ell(\theta) = \ln L(\theta).
$$

The maximum likelihood estimator for $\theta$ that maximizes $L(\theta)$, and equivalently, $\ell(\theta)$, since $\ln$ is an order-preserving transformation.

## Example 5.2.3

Let $X_1, X_2, \ldots, X_n$ be a random sample with pdf
$$
f(x; \theta) = \theta x^{\theta - 1} I_{(0,\infty)(x)},\quad\text{for }\theta > 0.
$$
Determine the MLE of $\theta$.

## Example 5.2.3 (cont)

## Example 5.2.3 (cont)

## Example 5.2.4

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim}N(\mu, \sigma^2)$. Determine the MLEs for $\mu$ and $\sigma^2$.

## Example 5.2.4 (cont)

## Example 5.2.4 (cont)

## Example 5.2.4 (cont)

## Example 5.2.4 (cont)

## Example 5.2.5 (Parameters in the Support of the Distribution)

Let $X_1, X_2, \ldots, X_n$ be a random sample from the distribution with pdf
$$
f(\stackrel{\rightarrow}{x}; \theta, \lambda) = \theta \lambda^{\theta}x^{-(\theta+1)}I_{(\lambda, \infty)}(x),
$$
with $\theta>0, \lambda > 0$. Find the MLEs for $\theta$ and $\lambda$.

## Example 5.2.5 (cont)

## Example 5.2.5 (cont)

## Example 5.2.5 (cont)

## Example 5.2.5 (cont)

## Example 5.2.5 (cont)

# 5.2.2 

::: {style="font-size: 250%;"}
The Invariance Property of MLEs
:::

## Definition 5.2.2

If $\hat{\theta}$ is the MLE of $\theta$, then the MLE of a function $\tau(\theta)$ is
$$
\widehat{\tau(\theta)} = \tau(\hat{\theta}).
$$
This is known as the **invariance property** of MLEs.

## Invariance examples

## Invariance examples (cont)

## Psuedo proof of invariance

## Psuedo proof of invariance (cont)

# 5.3

::: {style="font-size: 250%;"}
The Cram&eacute;r–Rao Lower Bound (CRLB)
:::

## CRLB Introduction

The CRLB is the minimum possible variance of an unbiased estimator of a parameter $\theta$ (or a function, $\tau(\theta)$).

If $\hat{\theta}$ is an unbiased estimator of $\theta$, then the CRLB tells us how small the variance of $\hat{\theta}$ can be.

- This lower bound may not be attainable.
- If an unbiased estimator does attain the associated CRLB, then it has the uniformly minimum variance amoung all unbiased estimators.

# 5.3.1

::: {style="font-size: 250%;"}
Statement of the CRLB and Derivation
:::

## The Cram&eacute;r–Rao Lower Bound

Let $X_1, X_2, \ldots, X_n$ be random variable with joint pdf $f(\stackrel{\rightarrow}{x}; \theta)$. Assume that the support of the distribution does not depend on $\theta$ and that $\theta$ is one-dimensional.

Consider estimating some function $\tau(\theta)$ and let $T=t(\stackrel{\rightarrow}{X})$ be any unbiased estimator of $\tau(\theta)$.

Then 
$$
\text{var}[T] \geq \frac{[\tau^{'}(\theta)]^2}{E\left[\left(\frac{\partial}{\partial\theta} \ln f(\stackrel{\rightarrow}{X}; \theta)\right)^2\right]},
$$
under certain regularity assumptions.

## Regularity assumptions for the CRLB

The regularity assumption for the CRLB are:

- $0 < E\left[\left(\frac{\partial}{\partial\theta} \ln f(\stackrel{\rightarrow}{X}; \theta)\right)^2\right] < \infty$,
- $\frac{\partial}{\partial\theta}\int f(\stackrel{\rightarrow}{x}; \theta) d\stackrel{\rightarrow}{x}=\int \frac{\partial}{\partial\theta} f(\stackrel{\rightarrow}{x}; \theta) d\stackrel{\rightarrow}{x}$
- $\frac{\partial}{\partial\theta} \ln f(\stackrel{\rightarrow}{x}; \theta)$ exists.

## CRLB notation

We denote the CRLB by
$$
\text{CRLB}_{\tau(\theta)}:=\frac{[\tau^{'}(\theta)]^2}{E\left[\left(\frac{\partial}{\partial\theta} \ln f(\stackrel{\rightarrow}{X}; \theta)\right)^2\right]}.
$$

Computation of the CRLB will simplify when the data are i.i.d., but the CRLB holds for more general joint pdfs.


## Definition 5.3.1

The Fisher information for a sample is defined as
$$
I_n(\theta) = E\left[\left(\frac{\partial}{\partial\theta} \ln f(\stackrel{\rightarrow}{X}; \theta)\right)^2\right].
$$

The Fisher information quantifies the amount of information the sample contains about $\theta$.

We can rewrite the CRLB of $\theta$ as
$$
\text{CRLB}_{\tau(\theta)} = \frac{[\tau^{'}(\theta)]^2}{I_n(\theta)}.
$$

## The Cauchy-Schwarz Inequality

For square-integrable functions $f$ and $g$,
$$
\left( \int f(x) g(x)\,dx \right)^2
\leq
\left( \int f(x)^2\,dx \right)
\left( \int g(x)^2\,dx \right)
$$
There are analagous Cauchy-Schwarz inequalities for sums and inner products.

## Proof of C-S inequality

## Proof of C-S inequality (cont)

## Proof of C-S inequality (cont)

## Proof of CRLB

## Proof of CRLB (cont)

## Proof of Equation 5.3.4

## Proof of Equation 5.3.4 (cont)

## Proof of Equation 5.3.4 (cont)

## Proof of Equation 5.3.4 (cont)

## Example 5.3.1

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} \text{Bernoulli}(p)$.

a. Find the CRLB for the variance of all unbiased estimators of $p$.
b. Find the CRLB for the variance of all unbiased estimators of $\tau(p) = p(1-p)$.

## Example 5.3.1 (cont)

## Example 5.3.1 (cont)

## Example 5.3.1 (cont)



# 5.3.2 

::: {style="font-size: 250%;"}
Computational Simplifications for the CRLB
:::

## Definition 5.3.2

In statistical inference, the **score function** is the derivative of the log-likelihood 
$$
S(\stackrel{\rightarrow}{X}) = \frac{\partial}{\partial\theta}\ln f(\stackrel{\rightarrow}{X}; \theta).
$$

## Property 0.

The expected value of the score function is zero. That is, 
$$
E\left[\frac{\partial}{\partial\theta}\ln f(\stackrel{\rightarrow}{X}; \theta)\right] = 0.
$$

## Property 0 (cont)

## Property 1

The Fisher information can be written in terms of a second deriviative. In particular, we have that
$$
E\left[\left(\frac{\partial}{\partial\theta} \ln f(\stackrel{\rightarrow}{X}; \theta)\right)^2\right] = -E\left[\frac{\partial^2}{\partial\theta^2}\ln f(\stackrel{\rightarrow}{X}; \theta)\right].
$$

## Property 1 (cont)

## Property 1 (cont)

## Property 1 (cont)

## Property 2

If $X_1, X_2, \ldots, X_n$ are i.i.d., then the "$n$-dimensional Fisher information" can be written as $n$ times the "one-dimensional Fisher information". That is,
$$
E\left[\left(\frac{\partial}{\partial\theta} \ln f(\stackrel{\rightarrow}{X}; \theta)\right)^2\right] \stackrel{iid}{=} nE\left[\left(\frac{\partial}{\partial\theta} \ln f(X_1; \theta)\right)^2\right],
$$
or
$$
I_n(\theta) \stackrel{iid}{=}nI_1(\theta).
$$

## Property 2 (cont)

## Property 2 (cont)

## Example 5.3.2

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim}\text{Gamma}(2,\beta)$.

Find the CRLB for the variance of all unbiased parameters of $\beta$.

## Example 5.3.2 (cont)

## Example 5.3.2 (cont)

## Example 5.3.2 (cont)

# 5.4

::: {style="font-size: 250%;"}
Asymptotic Properties of MLEs
:::

## MLE intution and large-sample properties

The quality of estimator should improve as our sample size increases.

MLEs have good large-sample properties.

## Definition 5.4.1

An unbiased estimator who variance attains the CRLB is said to be **efficient**.

The efficiency of an estimator $T$ of $\tau(\theta)$ is the ratio
$$
\frac{\text{CRLB}_\theta}{\text{var}(T)}.
$$
An efficient estimator has efficiency 1.

## MLEs have nice properties

Under certain regularity conditions, the MLE of $\theta$, $\hat{\theta}_n$, will have nice properties:

- $\hat{\theta}_n$ **exists** and is **unique**.
- $\hat{\theta}_n$ is a **consistent** estimator of $\theta$, i.e., $\hat{\theta}_n\stackrel{P}{\to} \theta$.
- $\hat{\theta}_n$ is **asymptotically unbiased** for $\theta$, i.e., $\lim_{n\to\infty} E[\hat{\theta}_n] = \theta$.
- $\hat{\theta}_n$ is **asymptotically efficient**, i.e., $\lim_{n\to\infty} \frac{\text{CRLB}_\theta}{\text{var}(\hat{\theta}_n)} = 1$.
- $\hat{\theta}_n$ is **asymptotically normal**, i.e., $\hat{\theta}_n \stackrel{asymp.}{\sim} N(\theta, \text{CRLB}_\theta)$.

## Regularity Conditions for MLEs

MLEs are consistent under the following assumptions (Casella and Berger, 2002):

- A1: **Correct Model**. $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} f(x; \theta)$, i.e., that is their true distribution.
- A2: **Identifiability**. $\theta_1 \neq \theta_2 \implies f(x;\theta_1) \neq f(x;\theta_2)$.
- A3: **Differentiability**. $f(x;\theta)$ is differentiable in $\theta$.
- A4: **Interior parameter**. The true parameter value $\theta_0$ is an interior point of the parameter space $\Theta$.

## Regularity Conditions for MLEs (cont)

To prove asymptotic normality and efficiency of the MLEs, we also need conditions A5 and A6:

- A5: **Smoothness (regularity)**.
    - The density $f(x; \theta)$ is three times differentiable with respect to $\theta$ and continuous, i.e., $\frac{\partial^3}{\partial\theta^3} f(x; \theta)$ exists and is continuous.
    - $\int f(x; \theta)\,dx$ can be differentiated three times under the integral sign, i.e., $\frac{\partial^3}{\partial\theta^3} \int f(x; \theta)\, dx =  \int \frac{\partial^3}{\partial\theta^3} f(x; \theta)\, dx.$
    
## Regularity Conditions for MLEs (cont)

- A6: **Boundedness**. For all $\theta \in \Theta$, there exists a $c > 0$ and a function $M(x)$ such that
$$
\left| \frac{\partial^3 \log f(x;\theta)}{\partial \theta^3} \right| \leq M(x)
$$
with $E_{\theta_0}[M(X)] < \infty$ for all $|\theta - \theta_0| < c$ and all $x$ in the support of $X$.

# 5.5

::: {style="font-size: 250%;"}
Uniformly Minimum Variance Unbiased Estimators (UMVUEs)
:::

## Definition 5.5.1

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} f(x; \theta)$. The **uniformly minimum variance unbiased estimator (UMVUE)** for $\theta$ is the unbiased estimator that has the smallest variance for all unbiased estimators.

"Uniformly" in $\theta$ means that this is true for all values of $\theta$.

We will learn how to find and built UMVUEs in certain contexts.

# 5.5.1

::: {style="font-size: 250%;"}
Sufficient Statistics
:::

## Definition 5.5.2

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} f(x; \theta)$. $S=s(\stackrel{\rightarrow}{X})$ is a **sufficient** statistic for estimating $\theta$ if the conditional distribution of $\stackrel{\rightarrow}{X}$ given $S$ does not depend on $\theta$.

Informally, if you know $S$, then seeing $\stackrel{\rightarrow}{X}$ does not give you any more information about $\theta$.

## Sufficient statistics in practice

See Example 5.5.1 for manually verifying a statistic is sufficient.

In practice, we find sufficient statistics using Neyman's Factorization Theorem

## Neyman's Factorization Theorem

If
$$
f(\stackrel{\rightarrow}{x}; \theta) = h(\stackrel{\rightarrow}{x})g(s(\stackrel{\rightarrow}{x}); \theta),
$$
where $h$ does not depend on $\theta$ and $g$ only depends on $\stackrel{\rightarrow}{x}$ through $s(\stackrel{\rightarrow}{x})$, then
$$
S = s(\stackrel{\rightarrow}{x})
$$
is sufficient for estimating $\theta$.

## Example 5.5.2

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} \text{Bernoulli}(p)$. Determine a sufficient statistic for $p$.

## Example 5.5.2 (cont)

## Example 5.5.2 (cont)

## Comments

- Sufficient statistics are not unique.
- $\stackrel{\rightarrow}{x}$ is a sufficient statistic but doesn't compress the data at all.
- We can always add more information and it will still be sufficient.
- We want to "compress" the data as much as possible, which foreshadows the concept of minimal sufficient statistics.
- Being sufficient for $\theta$ implies being sufficient for $\tau(\theta)$.

## Example 5.5.3

Let $X_1, X_2, \ldots, X_n \stackrel{i.i.d.}{\sim} \text{Uniform}(0, \theta)$. Find a sufficient statistic for $\theta$.

## Example 5.5.3 (cont)

## Example 5.5.3 (cont)

# 5.5.2

::: {style="font-size: 250%;"}
Conditional Expectation and Variance
:::

## Conditional expectation and variance notes

Let $X$ and $Y$ be random variables.

- $E[X]$ is a constant.
- $E[X \mid Y = y]$ is a function of $y$.
- $E[X \mid Y]$ is a random variable.
- $E[E[X \mid Y]] = E[X]$ (the law of iterated expectation).
- $\text{var}[X] = \text{var}[E[X\mid Y]] + E[\text{var}[X \mid Y]]$.

# 5.5.3 

::: {style="font-size: 250%;"}
The Rao-Blackwell Theorem
:::

## The Rao-Blackwell Theorem

Suppose we want to estimate some function of $\theta$ that we have named $\tau(\theta)$ based on some random sample $\stackrel{\rightarrow}{X}$.

Suppose that we have some unbiased estimator $T = t(\stackrel{\rightarrow}{X})$ so that
\begin{align}
E[T] = \tau(\theta).
\end{align}

Suppose that we have some sufficient statistic $S$ for the distribution.

Then
\begin{align}
T^* = E[T \mid S]
\end{align}

is also unbiased for $\tau(\theta)$ and $\text{var}(T^*) \leq \text{var}(T)$.

Furthermore, $T^*$ is a function of $S$ and the variance is strictly lower than the variance of $T$ unless $T^*$ and $T$ are the same.

## Proof of the Rao-Blackwell Theorem

## Proof of the Rao-Blackwell Theorem

## Proof of the Rao-Blackwell Theorem

## Proof of the Rao-Blackwell Theorem

## Example 5.5.4

Suppose that $X_1, X_2, \ldots, X_n\stackrel{i.i.d.}{\sim}\text{Poisson}(\lambda)$.

Find a quality unbiased estimator of $\tau(\lambda) = e^{-\lambda}$.

## Example 5.5.4 (cont)

## Example 5.5.4 (cont)

## Example 5.5.4 (cont)

## Example 5.5.4 (cont)

## Example 5.5.4 (cont)

## Example 5.5.4 (cont)


